### ISSUE TITLE
error importing the package

### ISSUE THREAD

**Issue by joslk12** [kiranparajuli589/vue3-ytframe#3]
When I add the line
`import VueYtframe from "vue3-ytframe"`

I'm getting this error:

> Could not find a declaration file for module 'vue3-ytframe'. 'node_modules/vue3-ytframe/dist/ytframe.umd.js' implicitly has an 'any' type.

**Comment by kiranparajuli589** [comment]
Hi, @joslk12, thx for reporting this. 

Can you please specify the
- packageVersion
- Vue version
- NodeJS version

being used while you noticed this issue?
